name: Danger
on: 
  pull_request:
    types: [opened, synchronize, edited]
concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
