name: Danger-Swift
on: pull_request
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: 417-72KI/danger-swiftlint@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
