name: Danger
on: pull_request
env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
jobs:
  danger:
    name: Danger
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: brew install danger/tap/danger-swift
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger-swift ci
