name: Test
on: 
  pull_request:
    paths:
      - '**.swift'
      - '.github/workflows/test.yml'
jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: set -o pipefail && swift test
