name: Test
on: 
  pull_request:
    paths:
      - '**.swift'
      - '.github/workflows/test.yml'
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  macOS:
    name: macOS
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: set -o pipefail && swift test
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.5
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: set -o pipefail && swift test --enable-test-discovery
