name: Test
on: 
  pull_request:
    paths:
      - '**.swift'
      - '.github/workflows/test.yml'
concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  macOS:
    name: macOS
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Packages
          key: ${{ runner.os }}-swift-package-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-package
            ${{ runner.os }}-
      - name: test
        run: |
          set -o pipefail && xcrun --sdk macosx \
          xcodebuild \
          -enableCodeCoverage YES \
          -scheme "SSGH" \
          -destination "platform=macOS" \
          -clonedSourcePackagesDirPath 'Packages' \
          -resultBundlePath 'test_output/SSGH.xcresult' \
          clean test | xcpretty
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: test_output/SSGH.xcresult
          show-passed-tests: false
          show-code-coverage: false
        if: success() || failure()
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.5.2, 5.5.3]
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swift-package-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-package
            ${{ runner.os }}-
      - name: build
        run: swift build
      - name: test
        run: swift test --enable-test-discovery
